spring:
  application:
    name: assignment-jaehyuk

  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    defer-datasource-initialization: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG

    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG

    com.assignment-jaehyuk: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

external:
  api:
    nager:
      base-url: https://date.nager.at/api/v3
      max-in-memory-size: 1048576  # 1MB (1024 * 1024)
      timeout: 3s
      retry:
        max-attempts: 2
        delay: 1s
      rate-limit:
        delay: 100ms

holiday:
  data-initialization:
    start-year: 2020
    end-year: 2025

  initializer:
    async: true
  
  scheduler:
    async: true
    concurrency:
      max-countries: 30
      max-years-per-country: 6
